### ISSUE TITLE
[Student Application] Ask for more information

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#123]
- Ask students what channel they heard of us from on the application
- Ask applicants whether they will be in Waterloo during the upcoming term
- Ask if they will be on school or co-op
- Ask if they are willing to design (totally optional)
- If they can come to the retreat and meet and greet event

**Comment by hkjayakumar** [comment]
> Text field or if we want to be fancy dropdown with optional textfield for other

> Facebook, Twitter, Medium, News Letter, University of Waterloo, Velocity, etc
