### ISSUE TITLE
Add Apply buttons on all pages

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#124]
People have expressed it being hard for them to find the application page.

Need designs and somebody to implement

**Comment by hkjayakumar** [comment]
Also see #44

**Comment by chrisjluc** [comment]
Yeah, I guess that issue is making it more visible, but this issue is stating this is the way to make it more visible. @johnsington thoughts?

**Comment by chrisjluc** [comment]
@johnsington where are the best places to put these buttons

**Comment by chrisjluc** [comment]
@johnsington @carol-yao do we still need to address this issue if we have the banner on every page? 

This is the PR with the banner and what it looks like:
https://github.com/uwblueprint/website/pull/139

**Comment by chrisjluc** [comment]
I'll make the call and say we don't need the apply buttons, because it seems redundant with the banner.
