### ISSUE TITLE
[Students] Consider modifying copy at the top of the page

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#13]
`
We are looking for talented University of Waterloo students who are motivated to empower nonprofits with their skills and abilities for social good.
`

Maybe say `... with their technical abilities and passion...`. We should have passion somewhere.

**Comment by bryanc208** [comment]
Changing to "We are looking for talented and **passionate** University of Waterloo students who are motivated to empower nonprofits **with their technical abilities** for social good."
