### ISSUE TITLE
[Students] Consider making copy more concise

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#14]
`We want to make sure that we are being completely transparent about what we look for in potential Blueprint members. This ensures that our community maintains the genuine and passionate culture that helps us drive our projects forward. To do this, we share the qualities that we focus on the most when engaging with potential candidates.`

I made it more concise, because people don't have time to read...

`We believe in transparency - especially when it comes to what we look for in Blueprint members. This ensures that our community maintains the genuine and passionate culture that helps us create successful projects. Here is what we value most when considering candidates.`

**Comment by bryanc208** [comment]
This makes it seem like we care about the candidate being transparent. I think the message that we want to get across is that **we** want to be transparent when it comes to what we look for in candidates.

**Comment by bryanc208** [comment]
Changing to "We believe in transparency - especially when it comes to what we look for in Blueprint members. **Being transparent about our criteria** ensures that our community maintains the genuine and passionate culture that helps us create successful projects. Here is what we value most when considering candidates."
