### ISSUE TITLE
[Landing Page]: Design (I think displaying team as 2 col would be better use of space/less scroll)

### ISSUE THREAD

**Issue by carol-yao** [uwblueprint/website#23]
![17195190_1331381430287278_1186393714_o](https://cloud.githubusercontent.com/assets/16827546/23670386/8b842cb6-0335-11e7-8c5f-165fef3a320e.jpg)

**Comment by bryanc208** [comment]
We would definitely have to decrease the size of each of the images and captions if we wanted to do that which may not offer the best experience. Here is what it looks like on an iPhone 6 screen styled for 2 pictures: 
<img width="393" alt="screen shot 2017-03-11 at 11 12 22 am" src="https://cloud.githubusercontent.com/assets/1473742/23826177/bf5be4a2-064b-11e7-860e-b7ded75d518a.png">

**Comment by bryanc208** [comment]
Closing as this task seems like it is also tested on the main site.
