### ISSUE TITLE
[Team][Student] Standardize VP titles

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#34]
- Standardize VP titles on team (current and alumni members)
- Fix Brianna's title (it's lowercase)
- Standardize VP External title on student and application pages.
- Also move john's profile below the VPs on the team page.

**Comment by hkjayakumar** [comment]
I looked at the VP titles at Cal Blueprint, and the titles on our website currently match what they have. However I think we should follow the standard of `VP [Role]`.

**Comment by chrisjluc** [comment]
Yeah, that's originally why we did it that way. I think it's fine standardizing the roles though.

**Comment by hkjayakumar** [comment]
`VP of operations` needs to be `VP operations`

**Comment by bryanc208** [comment]
Fixed.
