### ISSUE TITLE
[Meta Data] Fix thumbnail image for our website

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#35]
This is what it looks like in messenger.

<img width="620" alt="screen shot 2017-03-14 at 7 21 15 pm" src="https://cloud.githubusercontent.com/assets/5094088/23930735/775863ea-08eb-11e7-9524-793f518c5611.png">

**Comment by bryanc208** [comment]
What do we want to fix?

**Comment by chrisjluc** [comment]
Change the logo, it currently shows the old logo with the goose foot

**Comment by bryanc208** [comment]
We don't have a filled in logo like the one above in our Drive so we will need that first before this change can be made.

**Comment by chrisjluc** [comment]
@johnsington

**Comment by bryanc208** [comment]
Still waiting on assets.

**Comment by chrisjluc** [comment]
https://drive.google.com/drive/u/1/folders/0B9g6JRrVrgL3Rlp5aE5hbVN5ZDQ

**Comment by chrisjluc** [comment]
duplicate: https://github.com/uwblueprint/website/issues/35
