### ISSUE TITLE
Copy Suggestion

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#38]
This is what the Techyon people suggested:

suggestion on the copy, you can also call yourselves a non-profit organization, which might sound better than just "group of students". feel free to throw in a 'powered by techyon(link)' as well if you think we can give you any brand equity benefits

also, maybe consider changing "students" to something like 'hiring' or 'join us' or 'get involved'? since thats waht the entire students page is from what i'm reading

"University of Waterloo" reads better on that note than uWaterloo or UWaterloo

Meet Blueprint - we're a group of friendly folks at the University of Waterloo dedicated to using technology for the greater good.

consider changing "using" to "building"
... *building* technology for the greater good.

**Comment by bryanc208** [comment]
Hmm it seems like they are really pushing for "formalizing" our language which I am not really a fan of. At the heart of it, Blueprint is still a student run organization and there can be room for some light heartedness and casual vocabulary. I would consider these suggestions seriously and only make changes that we feel are *absolutely* necessary.

**Comment by hkjayakumar** [comment]
Under About, can we change 
>UW Blueprint is a group of students at the University of Waterloo

to

>We are a group of students at the University of Waterloo
---
Also, under Contact
>UW Blueprint is looking for non-profits who are in need of technological solutions, as well as partners interested in sponsoring UW Blueprint.

to

> We are looking for non-profits who are in need of technological solutions, as well as partners interested in sponsoring UW Blueprint.

**Comment by bryanc208** [comment]
^ Agree with those suggestions.

**Comment by chrisjluc** [comment]
Good suggestions hk!

**Comment by hkjayakumar** [comment]
I don't think we're considering the suggestions that were not implemented, so we can close this issue ?

**Comment by hkjayakumar** [comment]
Actually, I just realized we should change `using` to `building` here:
https://www.uwblueprint.org/team
