### ISSUE TITLE
[Admin] Fix portal issues

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#41]
Logging in, etc.

**Comment by chrisjluc** [comment]
This is what the page shows after logging in and selecting my blueprint gmail account
<img width="1192" alt="screen shot 2017-03-21 at 10 18 53 pm" src="https://cloud.githubusercontent.com/assets/5094088/24183268/9230fb52-0e84-11e7-8484-5c9a2ccb2bff.png">

<img width="590" alt="screen shot 2017-03-21 at 10 19 00 pm" src="https://cloud.githubusercontent.com/assets/5094088/24183269/948c4d48-0e84-11e7-8c57-9b6d1fa2d803.png">

**Comment by aaronte** [comment]
@bryanc208 Redirect URL is still redirecting to `uw-blueprint-dev` as you can see in the URL ^. Are all the variables set up correctly in production?

**Comment by bryanc208** [comment]
@aaronte Which redirect URL are we talking about here? The environment variables that are set up on prod are configured through CircleCI for which I don't see a redirect URL.

**Comment by aaronte** [comment]
@bryanc208 I'll take a look tonight

**Comment by aaronte** [comment]
@bryanc208 this needs to be set based on environment 

<img width="1036" alt="screen shot 2017-03-23 at 10 15 03 pm" src="https://cloud.githubusercontent.com/assets/5732620/24277835/33d0a114-1016-11e7-94fa-8867635e7bc5.png">

https://github.com/uwblueprint/website/blob/master/src/configs/config.ts

**Comment by aaronte** [comment]
This is fixed in prod.
