### ISSUE TITLE
[Application] Make the student application page more visible and accessible 

### ISSUE THREAD

**Issue by hkjayakumar** [uwblueprint/website#44]
I like this suggestion from #38 but instead of modifying the students link, we could make the application page available from the landing page itself ?

 > also, maybe consider changing "students" to something like 'hiring' or 'join us' or 'get involved'? since thats waht the entire students page is from what i'm reading

A 'join us' link will be really helpful, as long as we can distinguish between non-profits and students. There was also a suggestion from @kaivalyagandhi on the strategy doc

> can we have a shorter link? or like a redirect? something like uwblueprint.org/apply or uwblueprint.org/join is much more shareable.

**Comment by carol-yao** [comment]
POSSIBLE QUICK FIXES FOR NOW

![dark-grey-version](https://cloud.githubusercontent.com/assets/16827546/24435840/b3214282-1405-11e7-8977-200545f43c1f.png)
![new-logo-blue](https://cloud.githubusercontent.com/assets/16827546/24435842/b33168c4-1405-11e7-92a0-ba7edcd4d5f9.png)
![website-off-white](https://cloud.githubusercontent.com/assets/16827546/24435841/b32d0ea0-1405-11e7-8a01-5f46ab1fddc2.png)

**Comment by hkjayakumar** [comment]
@kaivalyagandhi comments
> the white one looks integrated as part of the design of the rest of the site! would suggest making the text "Applications to join the team now open, apply here! :tada:"

**Comment by hkjayakumar** [comment]
#70 added a short link, would still be nice to have a banner/link on the landing page
