### ISSUE TITLE
[Project] Link to Somo Project website and one liner about the sms tool

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#45]

**Comment by bryanc208** [comment]
Please provide link and one liner and label this as a "Feature Request"

**Comment by chrisjluc** [comment]
http://www.thesomoproject.org/

An SMS survey tool that will allow their entrepreneur to understand and
gauge the impact of their organizations.

**Comment by chrisjluc** [comment]
@kaivalyagandhi thoughts?
