### ISSUE TITLE
[Application] Add validation / warnings for users or make it a soft limit.

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#60]
Don't cut off the text they submit.

**Comment by bryanc208** [comment]
Is this bug verified? Seems like we don't have any code that causes this to happen. Maybe the person made a mistake and submitted their answer without completing it?

**Comment by chrisjluc** [comment]
What's the logic for the input? Does it allow more than 250 word /
character input or whatever it is?

**Comment by bryanc208** [comment]
Unless I'm missing something, as it stands, the code doesn't restrict word count.

**Comment by chrisjluc** [comment]
Can you dig into this? If there are no restrictiosn in which the
applicant's info gets cut off we can close this.

**Comment by hkjayakumar** [comment]
Performed two quick tests on the dev site, doesn't seem to be any restriction on word count. I think the candidate forgot to complete his answer.

You can check the test results on the admin portal. I think this issue can be closed

**Comment by bryanc208** [comment]
Thanks, HK.
