### ISSUE TITLE
[Admin] Disable the link on student applications if no resume was uploaded

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#63]

**Comment by bryanc208** [comment]
This should say that the resume link has an empty "href" property which causes it to redirect back to the main page. The fix should be to disable the link if no resume was uploaded.

**Comment by chrisjluc** [comment]
Is a website required for NPOs? If it's not, the application should also not have or show a link.

**Comment by hkjayakumar** [comment]
Yes, a website is required for NPOs
