### ISSUE TITLE
[Task] Move Xin Hao Zhang's application from dev to prod db

### ISSUE THREAD

**Issue by hkjayakumar** [uwblueprint/website#66]
The interesting thing about this application is that the candidate probably applied prior to changes made by @aaronte a few days ago since there is no timestamp on this application. But the application didn't show up on either portal until today.

There is a likelihood that this is connected to #67

**Comment by bryanc208** [comment]
To prevent unsafe db operations (sorry :( ) we should simply submit a new application through the website with the exact same values copied in to each field.

**Comment by hkjayakumar** [comment]
Submitted a new application on prod website using info from dev.
