### ISSUE TITLE
[Application] Include resume format in file name or restrict to PDFs

### ISSUE THREAD

**Issue by hkjayakumar** [uwblueprint/website#78]
Currently we do not see what the format of the resume is, but rely on the browser to render it properly. This causes problems when we receive resumes which are not PDFs

**Comment by bryanc208** [comment]
Sounds like a great idea. I think we can perhaps restrict it to PDFs (and maybe docx) but definitely including the format so that the browser knows how to open it is necessary.

**Comment by Ruxuan** [comment]
Enforce pdf format in https://github.com/uwblueprint/website/pull/229
